[2021-12-04 20:27:52,232: INFO : 01_generate_img_pkl] : >>>>> stage_01 started
[2021-12-04 20:27:52,239: INFO : all_utils] : Directory is created at artifacts\pickle_format_data
[2021-12-04 20:27:52,239: INFO : 01_generate_img_pkl] : state_01 completed >>>>>
[2021-12-04 20:43:28,048: INFO : 01_generate_img_pkl] : >>>>> stage_01 started
[2021-12-04 20:43:28,052: INFO : all_utils] : Directory is created at artifacts\pickle_format_data
[2021-12-04 20:43:28,056: INFO : 01_generate_img_pkl] : state_01 completed >>>>>
[2021-12-04 20:51:34,685: INFO : 01_generate_img_pkl] : >>>>> stage_01 started
[2021-12-04 20:51:34,689: INFO : all_utils] : Directory is created at artifacts\pickle_format_data
[2021-12-04 20:51:34,747: INFO : 01_generate_img_pkl] : Total Actor/Actress are : 100
[2021-12-04 20:51:34,751: INFO : 01_generate_img_pkl] : Total Images of Actor/Actress are : 8664
[2021-12-04 20:51:34,751: ERROR : 01_generate_img_pkl] : [Errno 2] No such file or directory: 'artifacts\\pickle_format_data\\img_pickle_file.pkl'
Traceback (most recent call last):
  File "d:\Study\data-science-portfolio\Face Matching Application 2\src\01_generate_img_pkl.py", line 55, in <module>
    params_path= parsed_args.params )
  File "d:\Study\data-science-portfolio\Face Matching Application 2\src\01_generate_img_pkl.py", line 40, in generate_data_pickle_file
    pickle.dump(filenames, open(pickle_file, 'rb'))
FileNotFoundError: [Errno 2] No such file or directory: 'artifacts\\pickle_format_data\\img_pickle_file.pkl'
[2021-12-04 20:53:08,635: INFO : 01_generate_img_pkl] : >>>>> stage_01 started
[2021-12-04 20:53:08,643: INFO : all_utils] : Directory is created at artifacts\pickle_format_data
[2021-12-04 20:53:08,734: INFO : 01_generate_img_pkl] : Total Actor/Actress are : 100
[2021-12-04 20:53:08,734: INFO : 01_generate_img_pkl] : Total Images of Actor/Actress are : 8664
[2021-12-04 20:53:08,742: INFO : 01_generate_img_pkl] : state_01 completed >>>>>
[2021-12-04 20:53:09,099: INFO : 01_generate_img_pkl] : >>>>> stage_01 started
[2021-12-04 20:53:09,103: INFO : all_utils] : Directory is created at artifacts\pickle_format_data
[2021-12-04 20:53:09,183: INFO : 01_generate_img_pkl] : Total Actor/Actress are : 100
[2021-12-04 20:53:09,183: INFO : 01_generate_img_pkl] : Total Images of Actor/Actress are : 8664
[2021-12-04 20:53:09,191: INFO : 01_generate_img_pkl] : state_01 completed >>>>>
[2021-12-04 22:36:27,855: INFO : 02_feature_extractor] : >>>>> stage_02 started
[2021-12-04 22:36:27,859: ERROR : 02_feature_extractor] : VGGFace() got an unexpected keyword argument 'include_tops'
Traceback (most recent call last):
  File "d:\Study\data-science-portfolio\Face Matching Application 2\src\02_feature_extractor.py", line 66, in <module>
    params_path= parsed_args.params )
  File "d:\Study\data-science-portfolio\Face Matching Application 2\src\02_feature_extractor.py", line 39, in feature_extractor
    pooling = poolings, input =(224,224,3) )
TypeError: VGGFace() got an unexpected keyword argument 'include_tops'
[2021-12-04 22:37:19,156: INFO : 02_feature_extractor] : >>>>> stage_02 started
[2021-12-04 22:37:19,164: ERROR : 02_feature_extractor] : VGGFace() got an unexpected keyword argument 'input'
Traceback (most recent call last):
  File "d:\Study\data-science-portfolio\Face Matching Application 2\src\02_feature_extractor.py", line 66, in <module>
    params_path= parsed_args.params )
  File "d:\Study\data-science-portfolio\Face Matching Application 2\src\02_feature_extractor.py", line 39, in feature_extractor
    pooling = poolings, input =(224,224,3) )
TypeError: VGGFace() got an unexpected keyword argument 'input'
[2021-12-04 22:37:50,865: INFO : 02_feature_extractor] : >>>>> stage_02 started
[2021-12-04 22:38:31,241: INFO : all_utils] : Directory is created at artifacts\extracted_features
[2021-12-04 22:38:31,245: INFO : 02_feature_extractor] : state_02 completed >>>>>
[2021-12-04 22:52:23,322: INFO : 02_feature_extractor] : >>>>> stage_02 started
[2021-12-04 22:52:25,407: INFO : all_utils] : Directory is created at artifacts\extracted_features
[2021-12-04 23:10:16,418: INFO : 02_feature_extractor] : state_02 completed >>>>>
